### ISSUE TITLE
AzureSMR -> AzureR?

### ISSUE THREAD

**Issue by hongooi73** [yueguoguo/r-on-azure#1]
AzureSMR is obsolete and no longer actively maintained, it might be time to switch to AzureRMR and friends.

**Comment by ldfreight** [comment]
which package should we now use to send and retrieve files in blob storage?

**Comment by hongooi73** [comment]
I'd recommend using AzureStor: https://github.com/Azure/AzureStor

**Comment by hongooi73** [comment]
Note that AzureSMR is now formally deprecated.

**Comment by RockScience** [comment]
Thank you for the information. What package should we use to interact with Data Lake gen1?
AzureStor doesnt seem to work.

**Comment by hongooi73** [comment]
For ADLSgen1, you can continue using AzureSMR. However, if possible I'd recommend moving over to ADLSgen2, which is where development work is focused. AzureStor supports ADLSgen2.
